server:
  # 后端端口
  port: 8080

spring:
  # 设置 thymeleaf
  thymeleaf:
    # 关闭缓存
    cache: false

  # 数据库配置
  datasource:
    # 用户名
    username: root
    # 密码
    password: Kunpeng@123456
    # mysql 的连接路径
    url: jdbc:mysql://localhost:3306/login_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    # 配置驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 配置映射文件
  type-aliases-package: com.study.entity # 配置实体类
  # mybatis 内置的配置
  configuration:
    # sql 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 实现数据库下划线字段与实体中驼峰属性映射
    map-underscore-to-camel-case: true

